apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: akkamicroservices.akka.lightbend.com
spec:
  group: akka.lightbend.com
  names:
    kind: AkkaMicroservice
    listKind: AkkaMicroserviceList
    plural: akkamicroservices
    singular: akkamicroservice
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                replicas:
                  type: integer
                  minimum: 1
                image:
                  type: string
                imagePullPolicy:
                  type: string
                httpPort:
                  type: string
                javaOptions:
                  type: string
                resources:
                  type: object
                  properties:
                    limits:
                      type: object
                      properties:
                        memory:
                          type: string
                    requests:
                      type: object
                      properties:
                        memory:
                          type: string
                        cpu:
                          type: string
                envSecret:
                  type: object
                  properties:
                    secretName:
                      type: string 