apiVersion: apps/v1
kind: Deployment
metadata:
  name: akka-operator
  namespace: lightbend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: akka-operator
  template:
    metadata:
      labels:
        app: akka-operator
    spec:
      serviceAccountName: akka-operator
      containers:
        - name: akka-operator
          image: lightbend/akka-cluster-operator:v1.1.3
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 256Mi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: akka-operator
  namespace: lightbend
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: akka-operator
rules:
  - apiGroups: ["akka.lightbend.com"]
    resources: ["akkamicroservices"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints", "persistentvolumeclaims", "events", "configmaps", "secrets"]
    verbs: ["*"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: akka-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: akka-operator
subjects:
  - kind: ServiceAccount
    name: akka-operator
    namespace: lightbend
